spring.application.name=PacketShield-DPI
# H2 Database settings
spring.datasource.url=jdbc:h2:mem:testdb
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=password
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect

# Isse Hibernate apne aap table bana dega
spring.jpa.hibernate.ddl-auto=update

# H2 Console enable karo (taki aap browser mein table dekh sako)
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console

# Logs mein SQL queries dekhne ke liye
spring.jpa.show-sql=true